name: EFVC

training:
  train_lambda: 1024

  batch_size: 8

  base_lr: 0.0002

  multi_frame_training: false

  stage_milestones: [10, 25, 40]
  lr_milestones: [45, 50, 55]
  lr_milestones_multi: [2, 4, 6]
  lr_gamma: 0.1

  flow_pretrain_dir: "../data/flow_pretrain_np/"

  resume: false
  ckpt: ""


datasets:
  vimeo90k:
    root: "D:/vimeo_septuplet"
    split_file: "sep_trainlist.txt"
  